name: contexts
on: [pull_request]
jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo ${{contains('hello','li')}}
          echo ${{startsWith('hello','he')}}
          echo ${{format('Hello {0} {1} {2}','World','!','!')}}
          eccho "this step is intentionally to fail in order to test functions"
      - name: test failure functions
        if: failure()
        run: echo "previous step failed but we able to execute this step by adding failure() function"
      - name: run after previous filure
        if: always()
        run: echo "previous step filed but this step was run"
  one:
    runs-on: ubuntu-latest
    steps:
     - name : Dump github contexts
       env:
         GITHUB_CONTEXT: ${{toJson(github)}}
       run: echo "$GITHUB_CONTEXT"
     - name: dump steps contexts
       env: 
         STEPS_CONTEXT: ${{toJson(steps)}}
       run: echo "$STEPS_CONTEXT"

  