name: contexts
on: [pull_request]
jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo ${{contains('hello','li')}}
          echo ${{startsWith('hello','he')}}
          echo ${{format('Hello {0} {1} {2}','World','!','!')}}
  one:
    runs-on: ubuntu-latest
    steps:
     - name : Dump github contexts
       env:
         GITHUB_CONTEXT: ${{toJson(github)}}
       run: echo "$GITHUB_CONTEXT"
     - name: dump steps contexts
       env: 
         STEPS_CONTEXT: ${{toJson(steps)}}
       run: echo "$STEPS_CONTEXT"

  