name: container
on: push
jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
      - name: step with docker-steps
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: '/bin/echo'
          args: 'Hello world'
      - name: step with docker-steps
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: 'node '
          args: -v
          