name: container
on: push
jobs:
  node-checker:
    runs-on: ubuntu-latest
    container: node:13.5.0-alpine3.10
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release