name: contexts
on: [pull_request]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
     - name : Dump github contexts
       env:
         GITHUB_CONTEXT: ${{toJson(github)}}
       run: echo "$GITHUB_CONTEXT"
     - name: dump steps contexts
       env: 
         STEPS_CONTEXT: ${{toJson(steps)}}
       run: echo "$STEPS_CONTEXT"